### Read al users
GET http://127.0.0.1:4000/product-api/products

### create product
POST  http://127.0.0.1:4000/product-api/products
Content-Type: application/json

{
    "name":"TV",
    "price":70000,
    "brand":"apple"
    
}

### Read al users
GET http://127.0.0.1:4000/user-api/users/6980cf4b454b610350165db7

### create user
POST http://127.0.0.1:4000/user-api/users
Content-Type: application/json

{
    "name":"ravi",
    "email":"ravi@mail.com",
    "password":"",
    "cart":[]
}

### Req to add product to the cart of the user doc
PUT http://localhost:4000/user-api/user-cart/user-id/6980cf4b454b610350165db7/product-id/69806bf114a734cea0e4a68d


//findOne ({email: req.body.email})
//findById(objid) **

###compare by id
GET http://localhost:4000/user-api/compare/69806bf114a734cea0e4a68d
